### ISSUE TITLE
May require jQuery Turbolinks

### ISSUE THREAD

**Issue by danaki** [the-teacher/the_sortable_tree#60]
Found strange bug. My menu editing interface has address /admin/menus, it contains both editing form and 2 level sortable tree list. The editing form ends with Cancel/Save buttons like so:

```
<a class="btn btn-default" href="/admin/menus">Cancel</a> or <input class="btn btn-primary" name="commit" type="submit" value="Save" />
```

First time I visit this page, everythig looks fine, sortable tree drag&drop works like charm.  But after I press Cancel, which leads me to the same URL where I just came from, nothing happens -- drag&drop is now broken until I press refresh or POST with Save.

After I installed https://github.com/kossnocorp/jquery.turbolinks the issue was gone, so I guess there's something related to the turbolink's javascript innitialization code.

gem "rails", "4.1"
gem "awesome_nested_set", "~> 3.0.0.rc.5"
gem "the_sortable_tree", "~> 2.5.0"
gem "jquery-rails"
gem "jquery-ui-sass-rails"

**Comment by the-teacher** [comment]
For my private projects I have a verison for TL.
Next time I have to release gem with support of TL. Thanks for your feedback!
