### ISSUE TITLE
Rebuild action not sync the client and server

### ISSUE THREAD

**Issue by sachin** [the-teacher/the_sortable_tree#66]
when we by droping a node under another node in a tree, rebuild action gets called which save the position and render nothing and status ok. 
This works fine as by droping of node it shown correcty on client and in rebuild it save the tree structure in database.
But if something breaks in rebuild action that is not notified to end user or drop is reverted.

So the tree structure on client and on server are not in sync

**Comment by the-teacher** [comment]
Maybe I will do something for that next time. Thanks for feedback!
