### ISSUE TITLE
Rebuild Method not working with namespaces.

### ISSUE THREAD

**Issue by juanortizthirdwave** [the-teacher/the_sortable_tree#72]
Since Ruby 2.0, `Object#respond_to?` returns `false` for protected methods.  
This will cause [`self.respond_to?(:sortable_collection)`](https://github.com/the-teacher/the_sortable_tree/blob/master/app/controllers/the_sortable_tree_controller.rb#L10) and [`self.respond_to?(:sortable_model)`](https://github.com/the-teacher/the_sortable_tree/blob/master/app/controllers/the_sortable_tree_controller.rb#L12) to return `false`, when `true` was expected. This case will happen when a namespaced controller overrides both methods `sortable_model` and `sortable_collection`.  
The code can be replaced with `self.methods.include?(:your_method)`. Let me know if you want me to send a pull request with the fixes.

**Comment by juandefelix** [comment]
Some additional info about it   
[http://tenderlovemaking.com/2012/09/07/protected-methods-and-ruby-2-0.html](http://tenderlovemaking.com/2012/09/07/protected-methods-and-ruby-2-0.html)

**Comment by essarraj-fouad** [comment]
the problem is in "constantize" method, he d'ont work without namespace.
we can create own constantize methode that support namespace like 
https://coderwall.com/p/jhrija/constantize-in-context
