### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by samro** [the-teacher/the_sortable_tree#76]
Hello,

I followed the read me, but i have this error : 
SQLite3::SQLException: no such column: lft: SELECT id, nom, parent_id FROM "menus"  ORDER BY lft ASC

I use rails 3.2, did i miss something ?

Thanks for your help.

**Comment by the-teacher** [comment]
please show me part of your `db/schema.rb` which represent `menus` table and ActiveRecord code from controller.

**Comment by samro** [comment]
All the parts that relate to <code>menus</code>

  create_table "menus", :force => true do |t|
    t.string   "nom"
    t.integer  "parent_id"
    t.integer  "niveau"
    t.string   "lien"
    t.string   "action"
    t.integer  "ordre"
    t.boolean  "boutonajouter"
    t.datetime "created_at",    :null => false
    t.datetime "updated_at",    :null => false
    t.integer  "created_by_id"
    t.integer  "updated_by_id"
  end
  add_index "menus", ["created_by_id"], :name => "index_menus_on_created_by_id"
  add_index "menus", ["nom", "parent_id"], :name => "index_menus_on_nom_and_parent_id"
  add_index "menus", ["nom"], :name => "index_menus_on_nom"
  add_index "menus", ["updated_by_id"], :name => "index_menus_on_updated_by_id"

  create_table "menus_roles", :id => false, :force => true do |t|
    t.integer "menu_id"
    t.integer "role_id"
  end

  add_index "menus_roles", ["menu_id", "role_id"], :name => "index_menus_roles_on_menu_id_and_role_id"

**Comment by craigsheen** [comment]
You need to have 'lft', 'rgt' and 'depth' columns for awesome nested set to work.

**Comment by samro** [comment]
Well... Sorry, i did'nt know this gem and i did'nt read the read me... I thought the_sortable_tree do all the job.

Thanks !
