### ISSUE TITLE
Возможность ограничить глубину дерева

### ISSUE THREAD

**Issue by saviokmua** [the-teacher/the_sortable_tree#80]
Здравствуйте. Хотелось бы использовать Ваш gem для управления категориями публикаций в блоге. 

Возможно но ли ограничить создания детей не более третьего уровня?

То есть запретить перетягивание, например элемента первого уровня с дочерним элементом на третий(так как в итоге будет глубина 4)?

**Comment by the-teacher** [comment]
здравствуйте.
На уровне интерфейса да.
На уровне контроллера нужно доопределять. Но обычно это им нет смысла заниматься в закрытой административной части сайта.

12.05.2016, 18:31, "saviokmua" <notifications@github.com>:
> Здравствуйте. Хотелось бы использовать Ваш gem для управления категориями публикаций в блоге.
>
> Возможно но ли ограничить создания детей не более третьего уровня?
>
> То есть запретить перетягивание, например элемента первого уровня с дочерним элементом на третий(так как в итоге будет глубина 4)?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

_______________________________
С уважением, Зыкин Илья
Web разработка с удовольствием!
тел.: 8-910-682-13-43
Успеха и Удачи!

**Comment by the-teacher** [comment]
Выглядит примерно так
![screen shot 2016-05-11 at 6 54 46 pm](https://cloud.githubusercontent.com/assets/496713/15221202/21a88df8-1873-11e6-90fb-eafb9693e989.png)

**Comment by saviokmua** [comment]
Спасибо! Интегрировал, все оболденно работает!

**Comment by the-teacher** [comment]
@saviokmua 👍
