### ISSUE TITLE
Use Node Link Click for Setting Hidden Input Form Value

### ISSUE THREAD

**Issue by perlmunger** [the-teacher/the_sortable_tree#82]
I am displaying a tree inside a bootstrap popover and would like to intercept the click on the node and simply pass the selected item's id to a hidden form input value via javascript rather than viewing the show view for the model object. I want the default visual rendering provided by the tree, but I just want to intercept the click. Is there a simple way to do this?

**Comment by the-teacher** [comment]
@perlmunger 
Hello!

**1.** You can create your own render helper. See how helpers look here
https://github.com/the-teacher/the_sortable_tree/tree/master/app/helpers
Just create yet another one in your project with your own HTML markup. There is simple example `https://github.com/the-teacher/the_sortable_tree/blob/master/app/helpers/render_tree_helper.rb`

**2.** Use this new Tree Render helper. Option `render_module` will help you. In my case name of render helper is `ShopCategoryRelsManagerHelper`

```slim
  .mb15.fs15 Brands
  ol.the-sortable-tree.the-sortable-tree--list(data={ max_levels: 5 })
    = sortable_tree all_brands, render_module: ShopCategoryRelsManagerHelper, used_in_ids: products_used_brands_ids
```

**3.** Add JS code to process clicks on your nodes and do what you want.

```js
// JS onready event
$(function(){
  $(window).on('click', '.js--my-tree-node', function(e){
     var node = $(e.currentTarget)
     
     // something like this here
     console.log(node)
     console.log( node.data('id') )
  })
})
```

Please close this issue if you got an answer or add more details below.
Thanks!

**Comment by perlmunger** [comment]
Thanks. That was what I needed.
